Add SumBy function
samber/lo pull request #120
Opened 2022-04-29 22:43 UTC by fossmo

Summarizes the values in a collection using the given return value from the iteration function.

2022-04-30 18:32 UTC, samber requested changes
Thanks for the contrib ;)

Can you move this code into `math.go` please ?

2022-04-30 19:14 UTC, fossmo commented on find.go
> +func SumBy[T any, R float32 | float64 | int | int8 | int16 | int32 | int64 | uint | uint8 | uint16 | uint32 | uint64](collection []T, iteratee func(T) R) R {
Fixed :-)

2022-04-30 19:14 UTC, fossmo commented on README.md
> +sum := lo.SumBy([]int16{4, 2, 3, 4, 5}, func(t int16) int16 {
Yes, I agree.

2022-05-02 12:26 UTC, samber approved these changes

2022-05-02 12:26 UTC, merged