Add Duplicate & DuplicateBy
samber/lo pull request #122
Opened 2022-05-02 10:56 UTC by CorentinClabaut

closes #121

2022-06-17 06:12 UTC, CorentinClabaut commented
That's a good point. 
I'm happy to make the change but before I'll wait on @samber input to be sure he is interested in the function being added.

2022-07-03 22:02 UTC, samber requested changes
Hi there,

`Duplicates` looks better than `Duplicate` 👍 

But since this function is not exactly the opposite of `Uniq`, I would name it `FindDuplicates` or `OnlyDuplicates`. WDYT ?

Also:
- is it a "search helper" (find.go) or a "slice helper" ?
- what about the opposite: `FindUniq`/`OnlyUniq` ?

Feel free to suggest other names.

2022-07-04 09:49 UTC, CorentinClabaut commented on slice.go
> +	for _, item := range collection {
That's a good point.
I didn't do it in a single loop to copy the first occurence of each duplicated elements.
But as the elements must be comparable I guess it doesn't make any difference.

2022-07-04 10:09 UTC, CorentinClabaut commented
Good points!

I'll rename Duplicate/DuplicateBy to FindDuplicates/FindDuplicatesBy and I'll create FindUniques/FindUniquesBy.
I'll also move these functions to find.go

2022-07-04 22:40 UTC, samber commented on slice.go
> +	for _, item := range collection {
hell yeah !

i didn't realize order was not conserved

2022-07-04 22:46 UTC, merged