chore: test coverage improvement
samber/lo pull request #240
Opened 2022-10-11 14:30 UTC by VictorAssunc

I noticed that some functions and function aliases weren't being completely covered by the tests, so I decided to create and improve some tests.

I decided to separate by commits instead of PRs to not spam the repository.

I'm not sure if I chose the best approach in each test, so I'm willing to change and learn more :)

2022-10-11 16:43 UTC, samber requested changes
hi @VictorAssunc and thanks for this first contrib

i made 1 comment

2022-10-11 16:43 UTC, samber commented on parallel/slice_test.go
> +	count := 0
please use 

```go
var counter uint64
atomic.AddUint64(&counter, 1)
```

instead

2022-10-20 17:13 UTC, VictorAssunc commented on parallel/slice_test.go
> +	count := 0
ok, i will change it

2022-10-21 12:11 UTC, VictorAssunc commented on parallel/slice_test.go
> +	count := 0
done ♻️

2022-10-22 17:03 UTC, samber approved these changes

2022-10-22 17:04 UTC, samber commented
I removed the parallel execution when you use a custom rand seed ;)

2022-10-22 17:05 UTC, merged