Add KeyBy
samber/lo pull request #33
Opened 2022-03-11 15:33 UTC by thetnaingtn

Add support for lodash's keyBy utility

2022-03-11 17:33 UTC, samber requested changes

2022-03-11 17:33 UTC, samber commented on README.md
> +### KeyValue
KeyValue -> KeyBy

2022-03-11 17:33 UTC, samber commented on README.md
> +- KeyBy
Could you move it into the "Slice" section, please?

Also from map.go to slice.go 🙏

2022-03-11 17:33 UTC, samber commented on map.go
> +func KeyBy[T any, V comparable](entries []T, iteratee func(T) V) map[V]T {
"V" to "K" please

It will be more understandable.

2022-03-11 17:33 UTC, samber commented on map_test.go
> +	"golang.org/x/tools/go/expect"
i'm pretty sure you can remove this line

2022-03-11 17:33 UTC, samber commented on map_test.go
> +	"golang.org/x/tools/go/expect"
i'm pretty sure you can remove this line

2022-03-11 17:37 UTC, samber commented
Oops, it is the same helper than lo.ToMap actually.

Can you rename ToMap to KeyBy please ?

2022-03-12 14:01 UTC, thetnaingtn commented
> Oops, it is the same helper than lo.ToMap actually.
> 
> Can you rename ToMap to KeyBy please ?

Sure thing. Now, I removed duplicate KeyBy and renamed ToMap utility to KeyBy.  @samber

2022-03-12 16:23 UTC, samber commented
Thanks for your help and sorry for the wrong name.

Let's merge ;)

2022-03-12 16:24 UTC, merged